FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.dashboard.txt .
RUN pip install --no-cache-dir -r requirements.dashboard.txt

# Copy dashboard files
COPY scripts/dashboard /app

# Expose port
EXPOSE 5000

# Run the dashboard
CMD ["python", "app.py"] 