version: '3.8'

services:
  strategy_manager:
    build: .
    environment:
      - AGENT_TYPE=strategy_manager
      - TRADING_MODE=DRY_RUN
      - INITIAL_BALANCE=10000
      - LOG_LEVEL=DEBUG
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8080:8080"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "5000:5000"